# Artificial Neural Network

### Importing the libraries

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [94]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [95]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')

In [96]:
X = dataset.iloc[ : , :-1].values
y = dataset.iloc[ : ,-1].values

In [97]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [98]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [99]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

###Feature Scaling

In [100]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
sc2 = StandardScaler()
X_train = sc1.fit_transform(X_train)
X_test = sc1.transform(X_test)
y_train = np.reshape(y_train, (len(y_train), 1))
y_test = np.reshape(y_test, (len(y_test), 1))
y_train = sc2.fit_transform(y_train)
y_test = sc2.transform(y_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [101]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [102]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the second hidden layer

In [103]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [104]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [105]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN model on the Training set

In [106]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 1.2390
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 0.3659
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0890
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0793
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0756
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0729
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0706
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0690
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0675
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0663
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0652
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 0.0645
Epoch 13/100


#Part 4 - Prediction the results

### Predicting the results of the Test set

In [107]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[-1.27 -1.35]
 [ 0.17  0.33]
 [ 0.47  0.4 ]
 ...
 [ 0.86  1.11]
 [-0.82 -0.96]
 [ 0.43  0.53]]


#Part 5 - Evaluating the model 

In [108]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.943900808510774